// Code generated by qtc from "spacers.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Various spacers
//

package parts

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamSpacer(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
<div class="py-4"></div>
`)
}

func WriteSpacer(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamSpacer(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func Spacer() string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteSpacer(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
