// Code generated by qtc from "standardHead.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// This is a standard page header
//

package parts

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamStandardHead(qw422016 *qt422016.Writer, title string) {
	qw422016.N().S(`
<title>`)
	qw422016.E().S(title)
	qw422016.N().S(`</title>
<script src="https://cdn.skypack.dev/@hotwired/turbo"></script>
`)
}

func WriteStandardHead(qq422016 qtio422016.Writer, title string) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamStandardHead(qw422016, title)
	qt422016.ReleaseWriter(qw422016)
}

func StandardHead(title string) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteStandardHead(qb422016, title)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
