// Code generated by qtc from "newPoll.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// New poll page
//

package templates

import (
	"github.com/codemicro/gopoll/internal/pages/internal/id"
)

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamNewPoll(qw422016 *qt422016.Writer) {
	qw422016.N().S(`

    <turbo-frame id="`)
	qw422016.E().S(id.MainBox)
	qw422016.N().S(`">
        <h2>Create a new poll</h2>
        <p>Blah blah</p>
    </turbo-frame>

`)
}

func WriteNewPoll(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamNewPoll(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func NewPoll() string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteNewPoll(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
