// Code generated by qtc from "simple.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// This is a simple page
//

package templates

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamSimple(qw422016 *qt422016.Writer, name string) {
	qw422016.N().S(`
<h1>Hello!</h1>
<p>Hi there `)
	qw422016.E().S(name)
	qw422016.N().S(`, it's good to have you.</p>
`)
}

func WriteSimple(qq422016 qtio422016.Writer, name string) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamSimple(qw422016, name)
	qt422016.ReleaseWriter(qw422016)
}

func Simple(name string) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteSimple(qb422016, name)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
